# For LASSO, standardization

# Notes

# 1. DATA LOADING & CLEANING
# codes are about data cleaning stuffs. you can simply starts from cs776/data/trajectory_cleaned2.csv

# 2. FEATURE SETUP
# If you are interested in seasonal feature (related to heat stress), you can generate it using month from "measurement_date" (it is your choice!)
# You can use raw DIM (numerical value) or lactation_stage (factor; generated by: DIM <= 60 ~ "early", 61 <= DIM <= 200 ~ "mid", other ~"late") (it is your choice!)

# 5. OUTER 5-FOLD CV WITH INNER GRID SEARCH
# For LASSO, we need to standardize features. To avoid data leakage, standardize using OUTER train stats only + scale fitted on inner train only — prevents leakage within inner CV
# There are double standardization => this might be changed/improved; but the basic idea was to avoid data leakage



# =============================================================================
# BHBA Prediction: Nested CV with Full Grid Search
# Outer CV: 5-fold  |  Inner CV: 3-fold
# Models: LM (baseline), LASSO (lambda grid), Random Forest, XGBoost
# Metrics: RMSE (validation), r² (reported)
# Feature Importance: LASSO (coef), RF (%IncMSE), XGBoost (SHAP)
# =============================================================================

library(dplyr)
library(glmnet)
library(randomForest)
library(xgboost)
library(SHAPforxgboost)
library(ggplot2)
library(tidyr)

# -----------------------------------------------------------------------------
# 1. DATA LOADING & CLEANING
# -----------------------------------------------------------------------------
data <- read.csv("/Users/sunny/Library/CloudStorage/Dropbox/Sunny/2024-current PhD/Course/2026 Spring/COMP SCI 776/projects/trajectory_cleaned.csv")

data <- data |>
  mutate(parity_group = case_when(
    lactation == 1 ~ "primiparous",
    lactation == 2 ~ "second_parity",
    lactation >= 3 ~ "mature_multiparous"
  ) |> factor(levels = c("primiparous", "second_parity", "mature_multiparous")))


data_clean <- data[data$bhba >= 0 & data$acetone >= 0, ]

set.seed(40)

data_sampled <- data_clean %>%
  group_by(idAnimale) %>%
  slice_sample(n = 1) %>%
  ungroup()

colnames(data_sampled)
nrow(data_sampled) #1612

summary(data_sampled$bhba)

write.csv(data_sampled, "trajectory_cleaned2.csv", quote=F, row.names=F)

# -----------------------------------------------------------------------------
# 2. FEATURE SETUP
# -----------------------------------------------------------------------------

features <- c("DIM", "acetone","urea", "parity_group",
              "fat", "casein", "protein", "lactose",
              "sfa", "ufa", "newly_fa", "mixed_fa", "preformed_fa",
              "c18_0", "c18_1", "scc_log",
              "ph", "freezing", "rennet", "k20", "a30", "iac")

model_data <- data_sampled[, c("bhba", features)]
model_data <- na.omit(model_data)
cat("Complete cases for modelling:", nrow(model_data), "\n")

# Matrix form for glmnet / xgboost (one-hot encodes lactation_stage)
X_full <- model.matrix(bhba ~ ., data = model_data)[, -1]
y_full <- model_data$bhba

# -----------------------------------------------------------------------------
# 3. HYPERPARAMETER GRIDS
# -----------------------------------------------------------------------------

# LASSO: alpha fixed at 1; lambda searched over explicit log-spaced grid
# glmnet.lambda.grid() is generated from the full outer-train data each fold
# so the grid is data-adaptive but the selection is done on inner folds only
lasso_lambda_grid <- exp(seq(log(1e-4), log(1), length.out = 100))

# Random Forest: mtry x nodesize = 15 combinations
rf_grid <- expand.grid(
  mtry     = c(3, 5, 7, 10, 14),
  nodesize = c(3, 5, 10)
)

# XGBoost: max_depth x eta x min_child_weight = 36 combinations
# subsample and colsample_bytree fixed at 0.8 (stable defaults)
xgb_grid <- expand.grid(
  max_depth        = c(3, 4, 5, 6),
  eta              = c(0.01, 0.05, 0.1),
  min_child_weight = c(3, 5, 10)
)

cat(sprintf("Grid sizes — LASSO lambda: %d | RF: %d | XGBoost: %d\n\n",
            length(lasso_lambda_grid), nrow(rf_grid), nrow(xgb_grid)))

# -----------------------------------------------------------------------------
# 4. HELPER FUNCTIONS
# -----------------------------------------------------------------------------
rmse_fn <- function(actual, pred) sqrt(mean((actual - pred)^2))
r2_fn   <- function(actual, pred) cor(actual, pred)^2

safe_best_nrounds <- function(cv_obj) {
  b <- cv_obj$best_iteration
  if (is.null(b) || length(b) == 0 || b < 1)
    b <- which.min(cv_obj$evaluation_log$test_rmse_mean)
  if (length(b) == 0 || b < 1) b <- 50L
  as.integer(b)
}

# -----------------------------------------------------------------------------
# 5. OUTER 5-FOLD CV WITH INNER GRID SEARCH
# -----------------------------------------------------------------------------
set.seed(42)
n <- nrow(model_data)
outer_idx <- sample(rep(1:5, length.out = n))

results <- data.frame(
  fold                 = 1:5,
  lm_rmse              = NA_real_,  lm_r2              = NA_real_,
  lasso_rmse           = NA_real_,  lasso_r2           = NA_real_,
  rf_rmse              = NA_real_,  rf_r2              = NA_real_,
  xgb_rmse             = NA_real_,  xgb_r2             = NA_real_,
  lasso_best_lambda    = NA_real_,
  rf_best_mtry         = NA_integer_,
  rf_best_nodesize     = NA_integer_,
  xgb_best_depth       = NA_integer_,
  xgb_best_eta         = NA_real_,
  xgb_best_mcw         = NA_integer_,
  xgb_best_nrounds     = NA_integer_
)

lasso_coef_list <- list()
rf_imp_list     <- list()
xgb_shap_list   <- list()

cat("=== Nested CV with Full Grid Search ===\n\n")

for (fold in 1:5) {
  cat(sprintf("--- Outer Fold %d/5 ---\n", fold))

  tr_idx <- which(outer_idx != fold)
  te_idx <- which(outer_idx == fold)

  X_tr   <- X_full[tr_idx, ];    X_te   <- X_full[te_idx, ]
  y_tr   <- y_full[tr_idx];      y_te   <- y_full[te_idx]
  df_tr  <- model_data[tr_idx, ]; df_te <- model_data[te_idx, ]

  # Inner fold assignment (reproducible per outer fold)
  set.seed(fold * 100)
  inner_idx <- sample(rep(1:3, length.out = length(y_tr)))

  # ------------------------------------------------------------------ #
  #  A. LINEAR MODEL — full model, no tuning (baseline)                 #
  # ------------------------------------------------------------------ #
  lm_fit  <- lm(bhba ~ ., data = df_tr)
  lm_pred <- predict(lm_fit, newdata = df_te)
  results$lm_rmse[fold] <- rmse_fn(y_te, lm_pred)
  results$lm_r2[fold]   <- r2_fn(y_te, lm_pred)
  cat("  LM done.\n")

  # ------------------------------------------------------------------ #
  #  B. LASSO — alpha=1 fixed, grid search over lambda                  #
  #     Standardize using OUTER train stats only (no leakage)           #
  # ------------------------------------------------------------------ #

  # Scale fitted on outer train, applied to outer test
  X_tr_sc  <- scale(X_tr)
  sc_center <- attr(X_tr_sc, "scaled:center")
  sc_scale  <- attr(X_tr_sc, "scaled:scale")
  # Guard against zero-variance columns (constant after one-hot encoding)
  sc_scale[sc_scale == 0] <- 1
  X_te_sc  <- scale(X_te, center = sc_center, scale = sc_scale)

  lasso_inner_rmse <- numeric(length(lasso_lambda_grid))

  for (g in seq_along(lasso_lambda_grid)) {
    lam <- lasso_lambda_grid[g]
    fold_rmses <- numeric(3)
    for (f in 1:3) {
      itr <- which(inner_idx != f); ite <- which(inner_idx == f)

      # Scale fitted on inner train only — prevents leakage within inner CV
      X_itr_sc    <- scale(X_tr_sc[itr, ])
      itr_center  <- attr(X_itr_sc, "scaled:center")
      itr_scale   <- attr(X_itr_sc, "scaled:scale")
      itr_scale[itr_scale == 0] <- 1
      X_ite_sc    <- scale(X_tr_sc[ite, ], center = itr_center, scale = itr_scale)

      fit  <- glmnet(X_itr_sc, y_tr[itr], alpha = 1, lambda = lam,
                     standardize = FALSE)
      pred <- as.vector(predict(fit, newx = X_ite_sc))
      fold_rmses[f] <- rmse_fn(y_tr[ite], pred)
    }
    lasso_inner_rmse[g] <- mean(fold_rmses)
  }

  best_lambda <- lasso_lambda_grid[which.min(lasso_inner_rmse)]
  results$lasso_best_lambda[fold] <- best_lambda

  # Refit on full outer-train (already scaled) with best lambda
  lasso_fit  <- glmnet(X_tr_sc, y_tr, alpha = 1, lambda = best_lambda,
                       standardize = FALSE)
  lasso_pred <- as.vector(predict(lasso_fit, newx = X_te_sc))
  results$lasso_rmse[fold] <- rmse_fn(y_te, lasso_pred)
  results$lasso_r2[fold]   <- r2_fn(y_te, lasso_pred)
  lasso_coef_list[[fold]]  <- coef(lasso_fit)   # coefficients on standardized scale
  cat(sprintf("  LASSO done. Best lambda=%.5f\n", best_lambda))

  # ------------------------------------------------------------------ #
  #  C. RANDOM FOREST — grid over mtry x nodesize                       #
  # ------------------------------------------------------------------ #
  rf_inner_rmse <- numeric(nrow(rf_grid))

  for (g in seq_len(nrow(rf_grid))) {
    mt <- rf_grid$mtry[g]; ns <- rf_grid$nodesize[g]
    fold_rmses <- numeric(3)
    for (f in 1:3) {
      itr <- which(inner_idx != f); ite <- which(inner_idx == f)
      rf_tmp <- randomForest(bhba ~ ., data = df_tr[itr, ],
                             ntree = 300, mtry = mt, nodesize = ns)
      fold_rmses[f] <- rmse_fn(y_tr[ite], predict(rf_tmp, df_tr[ite, ]))
    }
    rf_inner_rmse[g] <- mean(fold_rmses)
  }

  best_rf_g  <- which.min(rf_inner_rmse)
  best_mtry  <- rf_grid$mtry[best_rf_g]
  best_ns    <- rf_grid$nodesize[best_rf_g]
  results$rf_best_mtry[fold]     <- best_mtry
  results$rf_best_nodesize[fold] <- best_ns

  rf_final_fold <- randomForest(bhba ~ ., data = df_tr, ntree = 500,
                                 mtry = best_mtry, nodesize = best_ns,
                                 importance = TRUE)
  rf_pred <- predict(rf_final_fold, newdata = df_te)
  results$rf_rmse[fold] <- rmse_fn(y_te, rf_pred)
  results$rf_r2[fold]   <- r2_fn(y_te, rf_pred)
  rf_imp_list[[fold]]   <- importance(rf_final_fold, type = 1)
  cat(sprintf("  RF done. Best mtry=%d, nodesize=%d\n", best_mtry, best_ns))

  # ------------------------------------------------------------------ #
  #  D. XGBOOST — grid over max_depth x eta x min_child_weight          #
  # ------------------------------------------------------------------ #
  xgb_inner_rmse <- numeric(nrow(xgb_grid))

  for (g in seq_len(nrow(xgb_grid))) {
    params_g <- list(
      objective        = "reg:squarederror",
      eta              = xgb_grid$eta[g],
      max_depth        = xgb_grid$max_depth[g],
      subsample        = 0.8,
      colsample_bytree = 0.8,
      min_child_weight = xgb_grid$min_child_weight[g]
    )
    fold_rmses <- numeric(3)
    for (f in 1:3) {
      itr <- which(inner_idx != f); ite <- which(inner_idx == f)
      dtr_in <- xgb.DMatrix(X_tr[itr, ], label = y_tr[itr])
      dte_in <- xgb.DMatrix(X_tr[ite, ], label = y_tr[ite])
      xgb_cv_in <- xgb.cv(
        params = params_g, data = dtr_in,
        nrounds = 500, nfold = 3,
        early_stopping_rounds = 15,
        metrics = "rmse", verbose = 0
      )
      nr <- safe_best_nrounds(xgb_cv_in)
      m  <- xgb.train(params = params_g, data = dtr_in,
                      nrounds = nr, verbose = 0)
      fold_rmses[f] <- rmse_fn(y_tr[ite], predict(m, dte_in))
    }
    xgb_inner_rmse[g] <- mean(fold_rmses)
  }

  best_xgb_g <- which.min(xgb_inner_rmse)
  best_xgb_params <- list(
    objective        = "reg:squarederror",
    eta              = xgb_grid$eta[best_xgb_g],
    max_depth        = xgb_grid$max_depth[best_xgb_g],
    subsample        = 0.8,
    colsample_bytree = 0.8,
    min_child_weight = xgb_grid$min_child_weight[best_xgb_g]
  )
  results$xgb_best_depth[fold] <- xgb_grid$max_depth[best_xgb_g]
  results$xgb_best_eta[fold]   <- xgb_grid$eta[best_xgb_g]
  results$xgb_best_mcw[fold]   <- xgb_grid$min_child_weight[best_xgb_g]

  # Tune nrounds on full outer-train with best params
  dtrain_out <- xgb.DMatrix(X_tr, label = y_tr)
  dtest_out  <- xgb.DMatrix(X_te, label = y_te)
  xgb_cv_out <- xgb.cv(
    params = best_xgb_params, data = dtrain_out,
    nrounds = 1000, nfold = 3,
    early_stopping_rounds = 20,
    metrics = "rmse", verbose = 0
  )
  best_nr <- safe_best_nrounds(xgb_cv_out)
  results$xgb_best_nrounds[fold] <- best_nr

  xgb_fit_fold <- xgb.train(params = best_xgb_params, data = dtrain_out,
                              nrounds = best_nr, verbose = 0)
  xgb_pred <- predict(xgb_fit_fold, dtest_out)
  results$xgb_rmse[fold] <- rmse_fn(y_te, xgb_pred)
  results$xgb_r2[fold]   <- r2_fn(y_te, xgb_pred)

  # shap_vals <- shap.values(xgb_model = xgb_fit_fold, X_train = X_te)
  # xgb_shap_list[[fold]] <- shap_vals$mean_shap_score
  shap_matrix <- predict(xgb_fit_fold, dtest_out, predcontrib = TRUE)

  # Drop the last column (bias/intercept term xgboost appends)
  shap_matrix <- shap_matrix[, -ncol(shap_matrix)]
  xgb_shap_list[[fold]] <- colMeans(abs(shap_matrix))


  cat(sprintf("  XGBoost done. Best depth=%d, eta=%.2f, mcw=%d, nrounds=%d\n",
              xgb_grid$max_depth[best_xgb_g], xgb_grid$eta[best_xgb_g],
              xgb_grid$min_child_weight[best_xgb_g], best_nr))
}

# -----------------------------------------------------------------------------
# 6. RESULTS SUMMARY
# -----------------------------------------------------------------------------
cat("\n=== Nested 5x5 CV Performance Summary ===\n")
summary_tbl <- data.frame(
  Model     = c("Linear Model", "LASSO", "Random Forest", "XGBoost"),
  Mean_RMSE = round(c(mean(results$lm_rmse),    mean(results$lasso_rmse),
                       mean(results$rf_rmse),    mean(results$xgb_rmse)), 4),
  SD_RMSE   = round(c(sd(results$lm_rmse),      sd(results$lasso_rmse),
                       sd(results$rf_rmse),      sd(results$xgb_rmse)), 4),
  Mean_R2   = round(c(mean(results$lm_r2),      mean(results$lasso_r2),
                       mean(results$rf_r2),      mean(results$xgb_r2)), 4)
)
print(summary_tbl)

cat("\n=== Best Hyperparameters per Outer Fold ===\n")
print(results[, c("fold", "lasso_best_lambda",
                   "rf_best_mtry", "rf_best_nodesize",
                   "xgb_best_depth", "xgb_best_eta",
                   "xgb_best_mcw", "xgb_best_nrounds")])

mode_val <- function(x) as.numeric(names(sort(table(x), decreasing = TRUE))[1])
cat("\n=== Most Frequently Selected Hyperparameters (used for final refit) ===\n")
cat("LASSO       — lambda:    ", mode_val(results$lasso_best_lambda), "\n")
cat("RF          — mtry:      ", mode_val(results$rf_best_mtry), "\n")
cat("RF          — nodesize:  ", mode_val(results$rf_best_nodesize), "\n")
cat("XGBoost     — max_depth: ", mode_val(results$xgb_best_depth), "\n")
cat("XGBoost     — eta:       ", mode_val(results$xgb_best_eta), "\n")
cat("XGBoost     — mcw:       ", mode_val(results$xgb_best_mcw), "\n")

# -----------------------------------------------------------------------------
# 7. PLOTS — RMSE COMPARISON + PER-FOLD TRACE
# -----------------------------------------------------------------------------
p_rmse <- ggplot(summary_tbl,
                 aes(x = reorder(Model, Mean_RMSE), y = Mean_RMSE, fill = Model)) +
  geom_col(width = 0.6, show.legend = FALSE) +
  geom_errorbar(aes(ymin = Mean_RMSE - SD_RMSE,
                    ymax = Mean_RMSE + SD_RMSE), width = 0.25) +
  geom_text(aes(label = sprintf("%.4f", Mean_RMSE)),
            vjust = -0.7, size = 3.5, fontface = "bold") +
  scale_fill_brewer(palette = "Set2") +
  labs(title = "Nested 5x5 CV — Mean RMSE by Model",
       subtitle = "Error bars = +/-1 SD across outer folds",
       x = NULL, y = "RMSE") +
  theme_minimal(base_size = 13) +
  theme(plot.title = element_text(face = "bold"))
print(p_rmse)
ggsave("rmse_comparison.png", p_rmse, width = 7, height = 5, dpi = 150)

results_long <- results %>%
  select(fold, lm_rmse, lasso_rmse, rf_rmse, xgb_rmse) %>%
  pivot_longer(-fold, names_to = "model", values_to = "rmse") %>%
  mutate(model = recode(model,
    lm_rmse    = "Linear Model",
    lasso_rmse = "LASSO",
    rf_rmse    = "Random Forest",
    xgb_rmse   = "XGBoost"
  ))

p_folds <- ggplot(results_long, aes(x = fold, y = rmse,
                                     color = model, group = model)) +
  geom_line(linewidth = 1) + geom_point(size = 2.5) +
  scale_color_brewer(palette = "Set2") +
  scale_x_continuous(breaks = 1:5) +
  labs(title = "RMSE per Outer Fold",
       x = "Outer Fold", y = "RMSE", color = "Model") +
  theme_minimal(base_size = 13) +
  theme(plot.title = element_text(face = "bold"))
print(p_folds)
ggsave("rmse_per_fold.png", p_folds, width = 8, height = 5, dpi = 150)

# -----------------------------------------------------------------------------
# 8. FEATURE IMPORTANCE — LASSO
# -----------------------------------------------------------------------------
cat("\n=== LASSO Feature Importance ===\n")
all_coef_names <- rownames(lasso_coef_list[[1]])
lasso_coef_mat <- sapply(lasso_coef_list, function(cf) as.vector(cf))
rownames(lasso_coef_mat) <- all_coef_names

lasso_avg_coef <- rowMeans(abs(lasso_coef_mat))
lasso_imp_df <- data.frame(Feature = names(lasso_avg_coef),
                            Importance = lasso_avg_coef) %>%
  filter(Feature != "(Intercept)", Importance > 0) %>%
  arrange(desc(Importance))
print(lasso_imp_df)

p_lasso <- ggplot(lasso_imp_df,
                  aes(x = reorder(Feature, Importance), y = Importance)) +
  geom_col(fill = "#66C2A5") + coord_flip() +
  labs(title = "LASSO Feature Importance",
       subtitle = "Mean |coefficient| across outer folds (non-zero only)",
       x = NULL, y = "Mean |Coefficient|") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"))
print(p_lasso)
ggsave("lasso_importance.png", p_lasso, width = 7, height = 6, dpi = 150)

# -----------------------------------------------------------------------------
# 9. FEATURE IMPORTANCE — RANDOM FOREST
# -----------------------------------------------------------------------------
cat("\n=== Random Forest Feature Importance ===\n")
rf_imp_mat <- do.call(cbind, lapply(rf_imp_list, function(m) m[, 1]))
rf_avg_imp <- rowMeans(rf_imp_mat)
rf_imp_df <- data.frame(Feature = names(rf_avg_imp),
                         Importance = rf_avg_imp) %>%
  arrange(desc(Importance))
print(rf_imp_df)

p_rf <- ggplot(rf_imp_df,
               aes(x = reorder(Feature, Importance), y = Importance)) +
  geom_col(fill = "#FC8D62") + coord_flip() +
  labs(title = "Random Forest Feature Importance",
       subtitle = "Mean %IncMSE across outer folds",
       x = NULL, y = "%IncMSE") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"))
print(p_rf)
ggsave("rf_importance.png", p_rf, width = 7, height = 6, dpi = 150)

# -----------------------------------------------------------------------------
# 10. FEATURE IMPORTANCE — XGBOOST SHAP
# -----------------------------------------------------------------------------
cat("\n=== XGBoost SHAP Feature Importance ===\n")
shap_mat <- do.call(rbind, lapply(xgb_shap_list, function(s) s))
shap_avg <- colMeans(shap_mat)
shap_df <- data.frame(Feature = names(shap_avg),
                       SHAP_value = shap_avg) %>%
  arrange(desc(SHAP_value))
print(shap_df)

p_shap <- ggplot(shap_df,
                 aes(x = reorder(Feature, SHAP_value), y = SHAP_value)) +
  geom_col(fill = "#8DA0CB") + coord_flip() +
  labs(title = "XGBoost SHAP Feature Importance",
       subtitle = "Mean |SHAP| across outer folds",
       x = NULL, y = "Mean |SHAP value|") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"))
print(p_shap)
ggsave("xgb_shap_importance.png", p_shap, width = 7, height = 6, dpi = 150)

# -----------------------------------------------------------------------------
# 11. REFIT FINAL MODELS ON FULL DATA
#     Uses the most-frequently-selected hyperparameters from nested CV
# -----------------------------------------------------------------------------
cat("\n--- Refitting final models on full data ---\n")

final_lambda   <- mode_val(results$lasso_best_lambda)
final_mtry     <- mode_val(results$rf_best_mtry)
final_nodesize <- mode_val(results$rf_best_nodesize)
final_depth    <- mode_val(results$xgb_best_depth)
final_eta      <- mode_val(results$xgb_best_eta)
final_mcw      <- mode_val(results$xgb_best_mcw)

cat(sprintf(
  "Final params: LASSO lambda=%.5f | RF mtry=%d nodesize=%d | XGB depth=%d eta=%.2f mcw=%d\n",
  final_lambda, final_mtry, final_nodesize, final_depth, final_eta, final_mcw))

# Final LASSO — standardize full data (no leakage concern here, no test set)
X_full_sc    <- scale(X_full)
full_scale   <- attr(X_full_sc, "scaled:scale")
full_scale[full_scale == 0] <- 1
attr(X_full_sc, "scaled:scale") <- full_scale

lasso_all  <- glmnet(X_full_sc, y_full, alpha = 1, lambda = final_lambda,
                     standardize = FALSE)
cat("Non-zero LASSO coefficients on full data (standardized scale):\n")
coef_final <- coef(lasso_all)
print(coef_final[coef_final[, 1] != 0, , drop = FALSE])

# Final RF
rf_all <- randomForest(bhba ~ ., data = model_data, ntree = 500,
                        mtry = final_mtry, nodesize = final_nodesize,
                        importance = TRUE)

# Final XGBoost — tune nrounds on full data
final_xgb_params <- list(
  objective        = "reg:squarederror",
  eta              = final_eta,
  max_depth        = final_depth,
  subsample        = 0.8,
  colsample_bytree = 0.8,
  min_child_weight = final_mcw
)
dtrain_all <- xgb.DMatrix(X_full, label = y_full)
xgb_cv_all <- xgb.cv(
  params = final_xgb_params, data = dtrain_all,
  nrounds = 1000, nfold = 3,
  early_stopping_rounds = 20,
  metrics = "rmse", verbose = 0
)
final_nrounds <- safe_best_nrounds(xgb_cv_all)
xgb_all <- xgb.train(params = final_xgb_params, data = dtrain_all,
                      nrounds = final_nrounds, verbose = 0)
cat("Final XGBoost nrounds:", final_nrounds, "\n")

# SHAP beeswarm — top 15 features
shap_all  <- shap.values(xgb_model = xgb_all, X_train = X_full)
shap_long <- shap.prep(shap_contrib = shap_all$shap_score,
                        X_train = X_full, top_n = 15)

p_shap_bee <- shap.plot.summary(shap_long) +
  labs(title = "XGBoost SHAP Summary (Beeswarm)",
       subtitle = "Top 15 features — full dataset") +
  theme(plot.title = element_text(face = "bold"))
print(p_shap_bee)
ggsave("xgb_shap_beeswarm.png", p_shap_bee, width = 8, height = 7, dpi = 150)

# SHAP dependence plot for top feature
top_feat <- shap_df$Feature[1]
cat("SHAP dependence plot for:", top_feat, "\n")
p_shap_dep <- shap.plot.dependence(data_long = shap_long,
                                    x = top_feat, color_feature = "auto") +
  labs(title = paste("SHAP Dependence Plot:", top_feat)) +
  theme(plot.title = element_text(face = "bold"))
print(p_shap_dep)
ggsave("xgb_shap_dependence_top.png", p_shap_dep, width = 7, height = 5, dpi = 150)

cat("\n=== Done! ===\n")
cat("Output plots: rmse_comparison.png, rmse_per_fold.png,\n")
cat("              lasso_importance.png, rf_importance.png,\n")
cat("              xgb_shap_importance.png, xgb_shap_beeswarm.png,\n")
cat("              xgb_shap_dependence_top.png\n") 